# Setup

In [1]:
# Load the API key from .env and set the feed URLs we will call
import os
import requests
import pandas as pd
from dotenv import load_dotenv
from google.transit import gtfs_realtime_pb2

load_dotenv()
API_KEY = os.environ["TFNSW_API_KEY"]
HEADERS = {"Authorization": f"apikey {API_KEY}"}

TRIP_UPDATES_URL = "https://api.transport.nsw.gov.au/v2/gtfs/realtime/metro"
VEHICLE_POS_URL = "https://api.transport.nsw.gov.au/v2/gtfs/vehiclepos/metro"
ALERTS_URL = "https://api.transport.nsw.gov.au/v2/gtfs/alerts/metro"

# Trip Updates: fetch + decode

In [2]:
# Call the live trip updates feed and decode the protobuf bytes
resp = requests.get(TRIP_UPDATES_URL, headers=HEADERS)
print(resp.status_code, len(resp.content))

trip_feed = gtfs_realtime_pb2.FeedMessage()
trip_feed.ParseFromString(resp.content)

print(trip_feed.header)
print(len(trip_feed.entity))

200 49702
gtfs_realtime_version: "1.0"
incrementality: FULL_DATASET
timestamp: 1786780138

52

# Trip Updates: inspect a raw entity

In [3]:
# Look at one raw entity to see the real fields TfNSW sends
print(trip_feed.entity[0])

id: "0/2026-08-15T17:47:46+10:00/0241-001-104-014"
trip_update {
  trip {
    trip_id: "0241-001-104-014:1000"
    start_time: "16:57:00"
    start_date: "20260815"
    schedule_relationship: SCHEDULED
    route_id: "SMNW_M1"
    direction_id: 1
  }
  stop_time_update {
    stop_sequence: 1
    departure {
      delay: 0
      time: 1786777020
    }
    stop_id: "2155269"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: 0
      time: 1786777140
    }
    departure {
      delay: 25
      time: 1786777195
    }
    stop_id: "2155267"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: 0
      time: 1786777309
    }
    departure {
      delay: 28
      time: 1786777367
    }
    stop_id: "2155265"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: 4
      time: 1786777463
    }
    departure {
      delay: 27
      time: 1786777516
    }
    stop_id: "2153402"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: 6
      time: 1786777622
    }
    departure {
      delay: 30
      time: 1786777676
    }
    stop_id: "2153404"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: 5
      time: 1786777781
    }
    departure {
      delay: 26
      time: 1786777832
    }
    stop_id: "2154264"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: 26
      time: 1786777953
    }
    departure {
      delay: 26
      time: 1786777983
    }
    stop_id: "2154262"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: 26
      time: 1786778118
    }
    departure {
      delay: 26
      time: 1786778148
    }
    stop_id: "2126159"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: 3
      time: 1786778428
    }
    departure {
      delay: 25
      time: 1786778495
    }
    stop_id: "2121225"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 10
    arrival {
      delay: 2
      time: 1786778663
    }
    departure {
      delay: 2
      time: 1786778693
    }
    stop_id: "2113351"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 11
    arrival {
      delay: 2
      time: 1786778786
    }
    departure {
      delay: 2
      time: 1786778816
    }
    stop_id: "2113341"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 12
    arrival {
      delay: 2
      time: 1786778914
    }
    departure {
      delay: 2
      time: 1786778944
    }
    stop_id: "2113361"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 13
    arrival {
      delay: 2
      time: 1786779249
    }
    departure {
      delay: 2
      time: 1786779294
    }
    stop_id: "2067142"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 14
    arrival {
      delay: 2
      time: 1786779483
    }
    departure {
      delay: 2
      time: 1786779513
    }
    stop_id: "2065163"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 15
    arrival {
      delay: 2
      time: 1786779612
    }
    departure {
      delay: 2
      time: 1786779642
    }
    stop_id: "2060115"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 16
    arrival {
      delay: 2
      time: 1786779792
    }
    departure {
      delay: 2
      time: 1786779822
    }
    stop_id: "2000460"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 17
    arrival {
      delay: 2
      time: 1786779922
    }
    departure {
      delay: 2
      time: 1786779962
    }
    stop_id: "2000463"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 18
    arrival {
      delay: 2
      time: 1786780025
    }
    departure {
      delay: 24
      time: 1786780077
    }
    stop_id: "2000464"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 19
    arrival {
      delay: 24
      time: 1786780163
    }
    departure {
      delay: 24
      time: 1786780203
    }
    stop_id: "2000467"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 20
    arrival {
      delay: 24
      time: 1786780300
    }
    departure {
      delay: 24
      time: 1786780330
    }
    stop_id: "2017078"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 21
    arrival {
      delay: 24
      time: 1786780538
    }
    stop_id: "204471"
    schedule_relationship: SCHEDULED
  }
  vehicle {
    id: "RS038"
    label: "RS038"
    license_plate: "RS038"
  }
  timestamp: 1786780066
}

# Trip Updates: flatten to DataFrame preview

In [4]:
# Flatten every stop time update into one row so we can read it as a table
rows = []
for entity in trip_feed.entity:
    tu = entity.trip_update
    for stu in tu.stop_time_update:
        rows.append({
            "entity_id": entity.id,
            "trip_id": tu.trip.trip_id,
            "route_id": tu.trip.route_id,
            "start_date": tu.trip.start_date,
            "stop_sequence": stu.stop_sequence,
            "stop_id": stu.stop_id,
            "arrival_time": stu.arrival.time,
            "arrival_delay": stu.arrival.delay,
            "departure_time": stu.departure.time,
            "schedule_relationship": gtfs_realtime_pb2.TripUpdate.StopTimeUpdate.ScheduleRelationship.Name(stu.schedule_relationship),
        })

trip_updates_df = pd.DataFrame(rows)
print(trip_updates_df.shape)
trip_updates_df.head(20)

(1092, 10)

,entity_id,trip_id,route_id,start_date,stop_sequence,stop_id,arrival_time,arrival_delay,departure_time,schedule_relationship
0,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,1,2155269,0,0,1786777020,SCHEDULED
1,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,2,2155267,1786777140,0,1786777195,SCHEDULED
2,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,3,2155265,1786777309,0,1786777367,SCHEDULED
3,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,4,2153402,1786777463,4,1786777516,SCHEDULED
4,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,5,2153404,1786777622,6,1786777676,SCHEDULED
5,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,6,2154264,1786777781,5,1786777832,SCHEDULED
6,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,7,2154262,1786777953,26,1786777983,SCHEDULED
7,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,8,2126159,1786778118,26,1786778148,SCHEDULED
8,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,9,2121225,1786778428,3,1786778495,SCHEDULED
9,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,10,2113351,1786778663,2,1786778693,SCHEDULED
10,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,11,2113341,1786778786,2,1786778816,SCHEDULED
11,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,12,2113361,1786778914,2,1786778944,SCHEDULED
12,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,13,2067142,1786779249,2,1786779294,SCHEDULED
13,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,14,2065163,1786779483,2,1786779513,SCHEDULED
14,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,15,2060115,1786779612,2,1786779642,SCHEDULED
15,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,16,2000460,1786779792,2,1786779822,SCHEDULED
16,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,17,2000463,1786779922,2,1786779962,SCHEDULED
17,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,18,2000464,1786780025,2,1786780077,SCHEDULED
18,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,19,2000467,1786780163,24,1786780203,SCHEDULED
19,0/2026-08-15T17:47:46+10:00/0241-001-104-014,0241-001-104-014:1000,SMNW_M1,20260815,20,2017078,1786780300,24,1786780330,SCHEDULED

In [5]:
# Check the time range to catch bad or missing arrival times
pd.to_datetime(trip_updates_df["arrival_time"], unit="s").describe()

count                   1092
mean     2023-12-04 13:20:15
min      1970-01-01 00:00:00
25%      2026-08-15 07:19:20
50%      2026-08-15 07:53:58
75%      2026-08-15 08:33:37
max      2026-08-15 09:47:14
Name: arrival_time, dtype: object

# Vehicle Positions: fetch + decode

In [6]:
# Call the live vehicle positions feed and decode the protobuf bytes
resp = requests.get(VEHICLE_POS_URL, headers=HEADERS)
print(resp.status_code, len(resp.content))

vehicle_feed = gtfs_realtime_pb2.FeedMessage()
vehicle_feed.ParseFromString(resp.content)

print(vehicle_feed.header)
print(len(vehicle_feed.entity))

200 8337
gtfs_realtime_version: "1.0"
incrementality: FULL_DATASET
timestamp: 1786780144

27

# Vehicle Positions: inspect a raw entity

In [7]:
# Look at one raw vehicle entity to see its real fields
print(vehicle_feed.entity[0])

id: "0/2026-08-15T07:48:54Z/RS019"
vehicle {
  trip {
    trip_id: "0241-001-151-015:1000"
    start_time: "17:15:00"
    start_date: "20260815"
    schedule_relationship: SCHEDULED
    route_id: "SMNW_M1"
    direction_id: 0
  }
  position {
    latitude: -33.779644
    longitude: 151.086746
    bearing: 298.66
    speed: 27
  }
  current_stop_sequence: 12
  current_status: IN_TRANSIT_TO
  timestamp: 1786780134
  congestion_level: CONGESTION
  stop_id: "2113352"
  vehicle {
    id: "RS019"
    label: "RS019"
    license_plate: "RS019"
  }
  occupancy_status: MANY_SEATS_AVAILABLE
}

# Vehicle Positions: flatten to DataFrame preview

In [8]:
# Flatten every vehicle into one row so we can read it as a table
rows = []
for entity in vehicle_feed.entity:
    v = entity.vehicle
    rows.append({
        "entity_id": entity.id,
        "trip_id": v.trip.trip_id,
        "route_id": v.trip.route_id,
        "vehicle_id": v.vehicle.id or entity.id,
        "vehicle_label": v.vehicle.label,
        "lat": v.position.latitude,
        "lon": v.position.longitude,
        "bearing": v.position.bearing,
        "speed": v.position.speed,
        "current_stop_sequence": v.current_stop_sequence,
        "current_status": gtfs_realtime_pb2.VehiclePosition.VehicleStopStatus.Name(v.current_status),
        "timestamp": v.timestamp,
        "occupancy_status": gtfs_realtime_pb2.VehiclePosition.OccupancyStatus.Name(v.occupancy_status) if v.HasField("occupancy_status") else None,
    })

vehicle_pos_df = pd.DataFrame(rows)
print(vehicle_pos_df.shape)
vehicle_pos_df.head(20)

(27, 13)

,entity_id,trip_id,route_id,vehicle_id,vehicle_label,lat,lon,bearing,speed,current_stop_sequence,current_status,timestamp,occupancy_status
0,0/2026-08-15T07:48:54Z/RS019,0241-001-151-015:1000,SMNW_M1,RS019,RS019,-33.779644,151.086746,298.660004,27.0,12,IN_TRANSIT_TO,1786780134,MANY_SEATS_AVAILABLE
1,1/2026-08-15T07:48:56Z/RS041,0241-001-102-015:1000,SMNW_M1,RS041,RS041,-33.885834,151.204987,32.990002,18.0,2,IN_TRANSIT_TO,1786780136,MANY_SEATS_AVAILABLE
2,2/2026-08-15T06:58:13Z/RS010,M1-O-SYD_UP-CUD_DN-1-20260815-060013:X,SMNW_M1,RS010,RS010,-33.691898,150.905334,249.869995,0.0,20,IN_TRANSIT_TO,1786777093,FEW_SEATS_AVAILABLE
3,3/2026-08-15T07:27:19Z/RS018,0241-001-115-008:1000,SMNW_M1,RS018,RS018,-33.914135,151.166656,231.910004,0.0,21,STOPPED_AT,1786778839,FEW_SEATS_AVAILABLE
4,4/2026-08-15T07:48:53Z/RS043,0241-001-101-015:1000,SMNW_M1,RS043,RS043,-33.853973,151.202728,14.260000,23.0,6,IN_TRANSIT_TO,1786780133,FEW_SEATS_AVAILABLE
5,5/2026-08-15T07:48:55Z/RS035,0241-001-106-014:1000,SMNW_M1,RS035,RS035,-33.798210,151.180969,179.080002,0.0,13,STOPPED_AT,1786780135,FEW_SEATS_AVAILABLE
6,6/2026-08-15T07:48:55Z/RS030,0241-001-109-014:1000,SMNW_M1,RS030,RS030,-33.692738,150.924973,145.130005,10.0,2,IN_TRANSIT_TO,1786780135,FEW_SEATS_AVAILABLE
7,7/2026-08-15T07:48:54Z/RS029,M1-O-SYD_UP-CUD_DN-1-20260815-070414:X,SMNW_M1,RS029,RS029,-33.728077,150.986694,249.710007,0.0,16,STOPPED_AT,1786780134,MANY_SEATS_AVAILABLE
8,8/2026-08-15T07:49:00Z/RS020,M1-O-SYD_UP-CUD_DN-1-20260815-072414:X,SMNW_M1,RS020,RS020,-33.795952,151.149338,257.730011,27.0,9,IN_TRANSIT_TO,1786780140,STANDING_ROOM_ONLY
9,9/2026-08-15T07:49:00Z/RS026,0241-001-110-013:1000,SMNW_M1,RS026,RS026,-33.690136,150.913589,258.480011,25.0,20,IN_TRANSIT_TO,1786780140,FEW_SEATS_AVAILABLE
10,10/2026-08-15T07:48:58Z/RS008,0241-001-113-010:1000,SMNW_M1,RS008,RS008,-33.734627,150.963440,43.459999,13.0,4,IN_TRANSIT_TO,1786780138,MANY_SEATS_AVAILABLE
11,11/2026-08-15T07:48:54Z/RS009,0241-001-105-014:1000,SMNW_M1,RS009,RS009,-33.846397,151.203278,160.820007,23.0,15,IN_TRANSIT_TO,1786780134,FEW_SEATS_AVAILABLE
12,12/2026-08-15T07:48:52Z/RS022,0241-001-115-009:1000,SMNW_M1,RS022,RS022,-33.797081,151.180908,359.059998,0.0,9,STOPPED_AT,1786780132,FEW_SEATS_AVAILABLE
13,13/2026-08-15T07:34:18Z/RS036,M1-O-SYD_UP-CUD_DN-1-20260815-063614:X,SMNW_M1,RS036,RS036,-33.691898,150.905334,249.869995,0.0,21,STOPPED_AT,1786779258,FEW_SEATS_AVAILABLE
14,14/2026-08-15T07:48:52Z/RS042,0241-001-108-014:1000,SMNW_M1,RS042,RS042,-33.730606,151.016464,100.800003,27.0,7,IN_TRANSIT_TO,1786780132,MANY_SEATS_AVAILABLE
15,15/2026-08-15T07:48:56Z/RS038,0241-001-104-014:1000,SMNW_M1,RS038,RS038,-33.883003,151.207428,215.259995,11.0,18,IN_TRANSIT_TO,1786780136,FEW_SEATS_AVAILABLE
16,16/2026-08-15T07:09:24Z/RS044,M1-I-CUD_DN-SYD_UP-1-20260815-061118:X,SMNW_M1,RS044,RS044,-33.914135,151.166656,231.910004,0.0,21,STOPPED_AT,1786777764,MANY_SEATS_AVAILABLE
17,17/2026-08-15T07:48:52Z/RS040,0241-001-152-015:1000,SMNW_M1,RS040,RS040,-33.784653,151.127762,311.329987,6.0,11,IN_TRANSIT_TO,1786780132,FEW_SEATS_AVAILABLE
18,18/2026-08-15T07:48:54Z/RS033,M1-O-SYD_UP-CUD_DN-1-20260815-071214:X,SMNW_M1,RS033,RS033,-33.754101,151.061172,308.790009,27.0,13,IN_TRANSIT_TO,1786780134,FEW_SEATS_AVAILABLE
19,19/2026-08-15T07:48:50Z/RS011,M1-O-SYD_UP-CUD_DN-1-20260815-073214:X,SMNW_M1,RS011,RS011,-33.825386,151.198853,322.760010,4.0,7,IN_TRANSIT_TO,1786780130,MANY_SEATS_AVAILABLE

In [9]:
# Check how fresh the vehicle timestamps are
pd.to_datetime(vehicle_pos_df["timestamp"], unit="s").describe()

count                     27
mean     2026-08-15 07:43:57
min      2026-08-15 06:58:13
25%      2026-08-15 07:48:51
50%      2026-08-15 07:48:54
75%      2026-08-15 07:48:57
max      2026-08-15 07:49:00
Name: timestamp, dtype: object

# Service Alerts: fetch + decode

In [10]:
# Call the live alerts feed and decode the protobuf bytes
resp = requests.get(ALERTS_URL, headers=HEADERS)
print(resp.status_code, len(resp.content))

alerts_feed = gtfs_realtime_pb2.FeedMessage()
alerts_feed.ParseFromString(resp.content)

print(alerts_feed.header)
print(len(alerts_feed.entity))

200 8718
gtfs_realtime_version: "2.0"
incrementality: FULL_DATASET
timestamp: 1786780072

2

# Service Alerts: inspect a raw entity

In [11]:
# Look at one raw alert to see its real fields
print(alerts_feed.entity[0] if alerts_feed.entity else "no active alerts")

id: "36b04344-8521-595d-be19-05bbf93c0a9e"
alert {
  active_period {
    start: 1786723200
    end: 1786896053
  }
  informed_entity {
    agency_id: "SMNW"
    route_id: "SMNW_M1"
    direction_id: 1
  }
  informed_entity {
    agency_id: "SMNW"
    route_id: "SMNW_M1"
    direction_id: 0
  }
  cause: MAINTENANCE
  effect: MODIFIED_SERVICE
  url {
    translation {
      text: "https://transportnsw.info/alerts/details#/ems-75874"
      language: "en"
    }
  }
  header_text {
    translation {
      text: "Train trackwork on the T4 Eastern Suburbs Line may affect how you travel"
      language: "en"
    }
  }
  description_text {
    translation {
      text: "Saturday 15 and Sunday 16 August \nTrain trackwork on the T4 Eastern Suburbs Line may affect how you travel.\nBuses replace trains between Bondi Junction and Central, but do not stop at Martin Place.\nIf travelling to T4 Eastern Suburbs & Illawarra Line stations change at:\n- Gadigal for express buses from Town Hall to Bondi Junction\n- Central for buses to Kings Cross and Edgecliff, or trains to T4 Illawarra Line stations."
      language: "en"
    }
    translation {
      text: "<div><strong>Saturday 15 and Sunday 16 August&nbsp;</strong></div>\n<ul>\n<li>Train trackwork on the T4 Eastern Suburbs Line may affect how you travel.</li>\n<li>Buses replace trains between Bondi Junction and Central, but do not stop at Martin Place.</li>\n<li>If travelling to T4 Eastern Suburbs &amp; Illawarra Line stations change at:<br />- <strong>Gadigal</strong> for express buses from Town Hall to Bondi Junction<br />- <strong>Central</strong> for buses to Kings Cross and Edgecliff, or trains to T4 Illawarra Line stations.<br /><br /></li>\n<li><a href=\"https://transportnsw.info/trip-planner\">Plan your trip</a>&nbsp;before you travel for up-to-date real time information.&nbsp;You can also subscribe to <a href=\"https://transportnsw.info/travel-info/ways-to-get-around/train/about-trackwork#subscribe\">planned trackwork alerts</a>.</li>\n</ul>"
      language: "en/html"
    }
  }
}

# Service Alerts: flatten to DataFrame preview

In [12]:
# Flatten each alert into one row per affected route so we can read it as a table
rows = []
for entity in alerts_feed.entity:
    a = entity.alert
    header = a.header_text.translation[0].text if a.header_text.translation else None
    description = a.description_text.translation[0].text if a.description_text.translation else None
    route_ids = [ie.route_id for ie in a.informed_entity if ie.route_id] or [None]
    for route_id in route_ids:
        rows.append({
            "entity_id": entity.id,
            "cause": gtfs_realtime_pb2.Alert.Cause.Name(a.cause),
            "effect": gtfs_realtime_pb2.Alert.Effect.Name(a.effect),
            "header_text": header,
            "description_text": description,
            "route_id": route_id,
        })

alerts_df = pd.DataFrame(rows)
print(alerts_df.shape)
alerts_df.head(20)

(204, 6)

,entity_id,cause,effect,header_text,description_text,route_id
0,36b04344-8521-595d-be19-05bbf93c0a9e,MAINTENANCE,MODIFIED_SERVICE,Train trackwork on the T4 Eastern Suburbs Line...,Saturday 15 and Sunday 16 August \nTrain track...,SMNW_M1
1,36b04344-8521-595d-be19-05bbf93c0a9e,MAINTENANCE,MODIFIED_SERVICE,Train trackwork on the T4 Eastern Suburbs Line...,Saturday 15 and Sunday 16 August \nTrain track...,SMNW_M1
2,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",NSN_2a
3,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",NSN_2i
4,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",NSN_2k
5,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",WST_2c
6,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",WST_2d
7,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2b
8,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2c
9,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2d
10,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2e
11,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2f
12,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2g
13,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2h
14,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2i
15,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",IWL_2j
16,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",BNK_1c
17,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",BNK_2a
18,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",BNK_2b
19,7e669567-64e5-5fec-83a2-7332090518c3,UNKNOWN_CAUSE,UNKNOWN_EFFECT,Station Update - Central,"From Sunday to Thursday, between 10pm and 5am,...",BNK_2d

# Static GTFS: download combined NSW zip

In [13]:
# Download the full static schedule zip that covers all of NSW
import io
import zipfile

STATIC_GTFS_URL = "https://api.transport.nsw.gov.au/v1/publictransport/timetables/complete/gtfs"

resp = requests.get(STATIC_GTFS_URL, headers=HEADERS, timeout=180)
print(resp.status_code, len(resp.content))

static_zip = zipfile.ZipFile(io.BytesIO(resp.content))
print(static_zip.namelist())

200 297818554
['agency.txt', 'stops.txt', 'routes.txt', 'calendar.txt', 'calendar_dates.txt', 'shapes.txt', 'trips.txt', 'stop_times.txt', 'notes.txt', 'levels.txt', 'pathways.txt']

# Static GTFS: filter to Sydney Metro (agency_id SMNW)

In [14]:
# Keep only the routes, trips, stop times and stops that belong to Sydney Metro
with static_zip.open("routes.txt") as f:
    routes_df = pd.read_csv(f, dtype=str)
metro_routes_df = routes_df[routes_df.agency_id == "SMNW"]

with static_zip.open("trips.txt") as f:
    trips_df = pd.read_csv(f, dtype=str)
metro_trips_df = trips_df[trips_df.route_id.isin(metro_routes_df.route_id)]

metro_trip_ids = set(metro_trips_df.trip_id)
chunks = []
with static_zip.open("stop_times.txt") as f:
    for chunk in pd.read_csv(f, dtype=str, chunksize=200_000):
        matched = chunk[chunk.trip_id.isin(metro_trip_ids)]
        if not matched.empty:
            chunks.append(matched)
metro_stop_times_df = pd.concat(chunks, ignore_index=True)

with static_zip.open("stops.txt") as f:
    stops_df = pd.read_csv(f, dtype=str)
metro_stops_df = stops_df[stops_df.stop_id.isin(metro_stop_times_df.stop_id)]

print(metro_routes_df.shape, metro_trips_df.shape, metro_stop_times_df.shape, metro_stops_df.shape)

(1, 9) (1930, 11) (40442, 11) (42, 10)

# Static GTFS: preview routes/trips/stops

In [15]:
# Show a quick look at the filtered metro schedule data
display(metro_routes_df)
display(metro_trips_df.head())
display(metro_stops_df.head())

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_color,route_text_color,exact_times
3302,3-M1-sj2-1,SMNW,M1,M1 Metro North West and Bankstown Line,Sydney Metro Network,401,168388,FFFFFF,0

,route_id,service_id,trip_id,shape_id,trip_headsign,direction_id,block_id,wheelchair_accessible,route_direction,trip_note,bikes_allowed
105606,3-M1-sj2-1,TA+rs200+11,0241-001-101-002:1000,3-M1-sj2-1.4.R,Sydenham,1,NaN,1,Tallawong to Sydenham,NaN,NaN
105607,3-M1-sj2-1,TA+rs200+11,0241-001-101-003:1000,3-M1-sj2-1.8.H,Tallawong,0,NaN,1,Sydenham to Tallawong,NaN,NaN
105608,3-M1-sj2-1,TA+rs200+11,0241-001-101-004:1000,3-M1-sj2-1.4.R,Sydenham,1,NaN,1,Tallawong to Sydenham,NaN,NaN
105609,3-M1-sj2-1,TA+rs200+11,0241-001-101-005:1000,3-M1-sj2-1.9.H,Tallawong,0,NaN,1,Sydenham to Tallawong,NaN,NaN
105610,3-M1-sj2-1,TA+rs200+11,0241-001-101-006:1000,3-M1-sj2-1.5.R,Sydenham,1,NaN,1,Tallawong to Sydenham,NaN,NaN

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,level_id,platform_code
40,2000466,2000466,"Central Station, Platform 26",-33.88411728,151.20638050,NaN,200060,1,Level -3,NaN
41,2000467,2000467,"Central Station, Platform 27",-33.88414242,151.20643575,NaN,200060,1,Level -3,NaN
183,204471,204471,"Sydenham Station, Platform 1",-33.91370658,151.16719220,NaN,204420,1,NaN,1
184,204472,204472,"Sydenham Station, Platform 2",-33.91379507,151.16723974,NaN,204420,1,NaN,2
380,2121225,2121225,"Epping Station, Platform 5",-33.77287527,151.08227835,NaN,212110,1,Level -2,5